app = 'colig-pb'
primary_region = 'ams'

[build]
  image = "registry.fly.io/colig-pb:deployment-0b6f75fde286625b3dda4f6d026ffed7"

[http_service]
  auto_start_machines = true
  auto_stop_machines = true
  force_https = true
  internal_port = 8080
  min_machines_running = 1
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory = '512mb'
  memory_mb = 512
  processes = ['app']
  size = 'shared-cpu-1x'

[mounts]
  source = "pb_data"
  destination = "/pb/pb_data"
