app = 'colig-pb'
primary_region = 'ams'

[build]
  image = "pocketbase/pocketbase:latest"

[http_service]
  auto_start_machines = true
  auto_stop_machines = true
  force_https = true
  internal_port = 8080
  min_machines_running = 1
  processes = ['app']

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/api/health"

[env]
  PB_MAX_REQUEST_BODY = "209715200"

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory = '1gb'
  processes = ['app']
  size = 'shared-cpu-1x'

[mounts]
  source = "pb_data"
  destination = "/pb/pb_data"
